# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "vsphere" {
  user           = "admin@company.local"
  password       = "MyAwesomePassword"
  vsphere_server = "0.0.0.0"
  allow_unverified_ssl = true
}
